# Generated by Django 5.1.2 on 2024-11-17 02:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingqueue',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='queue', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='confirm_users',
            field=models.ManyToManyField(blank=True, related_name='confirm_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
