# Generated by Django 5.1.2 on 2024-11-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_alter_usergroup_options_alter_usergroup_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingQueueGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matchingQueues', models.ManyToManyField(related_name='matching', to='matching.matchingqueue')),
            ],
        ),
    ]
