# Generated by Django 5.1.2 on 2024-11-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_matchingqueuegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingqueuegroup',
            name='matchingQueues',
            field=models.ManyToManyField(blank=True, related_name='matching', to='matching.matchingqueue'),
        ),
    ]
