# Generated by Django 5.1.2 on 2024-11-06 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_alter_matchingqueuegroup_matchingqueues'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingqueue',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='matchingqueue',
            name='user',
        ),
        migrations.DeleteModel(
            name='MatchingQueueGroup',
        ),
        migrations.AddField(
            model_name='matchingqueue',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='queue', to=settings.AUTH_USER_MODEL),
        ),
    ]
