# Generated by Django 5.1.2 on 2024-11-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_matchingqueue_name_remove_matchingqueue_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchingqueue',
            old_name='user',
            new_name='users',
        ),
    ]
