# Generated by Django 5.1.2 on 2024-11-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_rename_user_matchingqueue_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
