# Generated by Django 5.1.2 on 2024-11-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0007_usergroup_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
