# Generated by Django 5.1.2 on 2024-11-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0009_matchrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchrequest',
            name='users',
        ),
    ]
