# Generated by Django 5.1.2 on 2024-11-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0010_remove_matchrequest_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='name',
            field=models.CharField(default='match_request', max_length=100, unique=True),
        ),
    ]
