# Generated by Django 5.1.2 on 2024-10-23 14:25

import my_auth.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_card_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='student_card_image',
            field=models.ImageField(blank=True, null=True, upload_to=my_auth.utils.secure_upload_to),
        ),
    ]
