# Generated by Django 5.1.2 on 2024-11-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='enrolled_student',
            field=models.BooleanField(default=False),
        ),
    ]
