# Generated by Django 5.1.2 on 2024-10-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='private_media/student_cards/'),
        ),
    ]
