# Generated by Django 5.1.2 on 2024-10-29 11:18

import my_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_customuser_student_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_card_image',
            field=models.ImageField(blank=True, null=True, upload_to=my_app.models.user_directory_path),
        ),
    ]
