# Generated by Django 5.1.2 on 2024-11-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_customuser_join_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
