# Generated by Django 5.1.2 on 2024-10-26 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_customuser_student_card_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='student_card_image',
        ),
    ]
