# Generated by Django 5.1.2 on 2024-10-30 04:17

import my_app.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_customuser_student_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_card_image',
            field=models.ImageField(blank=True, null=True, storage=my_app.storages.PrivateMediaStorage(), upload_to='student_cards/'),
        ),
    ]
