# Generated by Django 5.1.2 on 2024-11-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_customuser_student_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='join_room',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
